[features]
seeds = false
skip-lint = false

[programs.localnet]
popcow_token = "PopCow1111111111111111111111111111111111111"
cowguard_insurance = "CowGuard1111111111111111111111111111111111"
popcow_staking = "PopStake1111111111111111111111111111111111"

[programs.devnet]
popcow_token = "PopCow1111111111111111111111111111111111111"
cowguard_insurance = "CowGuard1111111111111111111111111111111111"
popcow_staking = "PopStake1111111111111111111111111111111111"

[programs.mainnet]
popcow_token = "PopCow1111111111111111111111111111111111111"
cowguard_insurance = "CowGuard1111111111111111111111111111111111"
popcow_staking = "PopStake1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
