[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
cowguard_insurance = "212XVhDqD21uFt1DfCuJ7WkVjcZZQCZRHDi3qeXTCqCH"
multi_asset_staking = "7qpcKQQuDYhN51PTXebV8dpWY8MxqUKeFMwwVQ1eFQ75"

[programs.devnet]
cowguard_insurance = "212XVhDqD21uFt1DfCuJ7WkVjcZZQCZRHDi3qeXTCqCH"
multi_asset_staking = "7qpcKQQuDYhN51PTXebV8dpWY8MxqUKeFMwwVQ1eFQ75"

[programs.mainnet]
cowguard_insurance = "212XVhDqD21uFt1DfCuJ7WkVjcZZQCZRHDi3qeXTCqCH"
multi_asset_staking = "7qpcKQQuDYhN51PTXebV8dpWY8MxqUKeFMwwVQ1eFQ75"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/zyj_dev/.config/solana/soldev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
