[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
popcow_token = "GB13aFFGs6G76dSWWNwHfH596npdwFcxkR5x4Ur4uBjS"
cowguard_insurance = "3vq7cmrWBVQZF11mHCKnDhppSyyBy9xstbz6tzZqDYcg"
popcow_staking = "4pMUmKCTvxCiM6ccGyc851yhyKnaKfJ3q2umLhyZ9Y2d"
token_vesting = "FKmtGh85bPYWRCyiJc8rHN6kohJWYgrkWvc8CtXAyz8n"
yield_vault = "ECAnyfJmCxVxUSgv4MW7uvAkMophVnG5VTvEAgQt2vrP"
multi_asset_staking = "EUN7ptUWascGEbBgFVQTxmFWzMSoN95YG5JGvabNtKYF"
reputation_registry = "6RpDY1sJJyQcTkYqr3myYbLuCA5H9SLeGonyRUBhBbWt"
governance = "5QCNr7vD639eE1R3rbts78qYZQEyc3L8XJriHNcLNyLW"
points_system = "2zv8gpnD7DYogiDb591uceav7Rkxfqz5aCK18hMqPCxH"
referral_system = "Cd2NZkSS5K4kqyWQcdaGv8deE8k75JrWjwU3byQRqEju"

[programs.devnet]
popcow_token = "GB13aFFGs6G76dSWWNwHfH596npdwFcxkR5x4Ur4uBjS"
cowguard_insurance = "3vq7cmrWBVQZF11mHCKnDhppSyyBy9xstbz6tzZqDYcg"
popcow_staking = "4pMUmKCTvxCiM6ccGyc851yhyKnaKfJ3q2umLhyZ9Y2d"
token_vesting = "FKmtGh85bPYWRCyiJc8rHN6kohJWYgrkWvc8CtXAyz8n"
yield_vault = "ECAnyfJmCxVxUSgv4MW7uvAkMophVnG5VTvEAgQt2vrP"
multi_asset_staking = "EUN7ptUWascGEbBgFVQTxmFWzMSoN95YG5JGvabNtKYF"
reputation_registry = "6RpDY1sJJyQcTkYqr3myYbLuCA5H9SLeGonyRUBhBbWt"
governance = "5QCNr7vD639eE1R3rbts78qYZQEyc3L8XJriHNcLNyLW"
points_system = "2zv8gpnD7DYogiDb591uceav7Rkxfqz5aCK18hMqPCxH"
referral_system = "Cd2NZkSS5K4kqyWQcdaGv8deE8k75JrWjwU3byQRqEju"

[programs.mainnet]
popcow_token = "GB13aFFGs6G76dSWWNwHfH596npdwFcxkR5x4Ur4uBjS"
cowguard_insurance = "3vq7cmrWBVQZF11mHCKnDhppSyyBy9xstbz6tzZqDYcg"
popcow_staking = "4pMUmKCTvxCiM6ccGyc851yhyKnaKfJ3q2umLhyZ9Y2d"
token_vesting = "FKmtGh85bPYWRCyiJc8rHN6kohJWYgrkWvc8CtXAyz8n"
yield_vault = "ECAnyfJmCxVxUSgv4MW7uvAkMophVnG5VTvEAgQt2vrP"
multi_asset_staking = "EUN7ptUWascGEbBgFVQTxmFWzMSoN95YG5JGvabNtKYF"
reputation_registry = "6RpDY1sJJyQcTkYqr3myYbLuCA5H9SLeGonyRUBhBbWt"
governance = "5QCNr7vD639eE1R3rbts78qYZQEyc3L8XJriHNcLNyLW"
points_system = "2zv8gpnD7DYogiDb591uceav7Rkxfqz5aCK18hMqPCxH"
referral_system = "Cd2NZkSS5K4kqyWQcdaGv8deE8k75JrWjwU3byQRqEju"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/zyj_dev/.config/solana/soldev.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
